### ISSUE TITLE
BUG: Box selection color disappeared!

### ISSUE THREAD

**Issue by YIRU69** [tefkah/zotero-night#33] opened 2022-05-15 05:04 UTC
![1](https://user-images.githubusercontent.com/48148292/168458080-53d3d1c5-cb4b-4d6d-85dc-805f6e831ea8.gif)

**Comment by zjpzhao** [comment] 2022-06-20 08:09
+1, the same bug

**Comment by tefkah** [comment] 2022-07-27 18:19
duplicate of #32, should be fixed in 4.11!

**Closed by tefkah** 2022-07-27 18:19 UTC
