### ISSUE TITLE
[BUG] Didn't work on ubuntu20.04

### ISSUE THREAD

**Issue by Bailey-24** [tefkah/zotero-night#71] opened 2022-09-19 07:13 UTC
**Describe the bug**
The plugins didn't work in zotero pdf reader on ubuntu20.04.

**To Reproduce**
1. Go to download zotero-night-0.4.16.xpi
2. Click on install zotero-night-0.4.16.xpi
3. Scroll down to 'restart'
4. Change dark mode. See error. The annotation didn't work

**Expected behavior**
I want the  annotation in dark mode.

**Screenshots**
In the right, there is white.
![image](https://user-images.githubusercontent.com/72083251/190971007-f2c141cb-a0dc-4d5e-9e60-f320876ee63d.png)

**OS (MacOS XX.xx [specify Intel or Silicon], Windows, Linux [specify distro/package type]:**
ubuntu20.04

**Zotero Night version (please check that you are on the latest version)**
zotero-night-0.4.16.xpi

**Additional context**
zotero version is 6.0.13
I use `sudo apt-get install zotero` to install zotero.

**Comment by tefkah** [comment] 2022-09-22 15:23
Duplicate of #37, will fix soon!

**Closed** 2022-09-23 01:47 UTC
Labels: bug
