### ISSUE TITLE
under the night mode, when select an entry and press "shift" simutaneously,The location of the folder where the document is located cannot be highlighted

### ISSUE THREAD

**Issue by Xieleilab** [tefkah/zotero-night#22] opened 2022-05-04 08:22 UTC
under the night mode, when select an entry and press "shift" simutaneously,The location of the folder where the document is located cannot be highlighted

**Comment by tefkah** [comment] 2022-07-27 18:26
This seems like a duplicate of #39 , which should be fixed as of 4.10!

**Closed by tefkah** 2022-07-27 18:26 UTC
